/** @format */

export const aytSubjects = [
	{
		code: "LITERATURE",
		name: "Türk Dili ve Edebiyatı",
		slug: "ayt-literature",
		color: "#db2777",
		icon: "PenTool",
		sortOrder: 1,
		topics: [
			{
				name: "Edebiyat Bilgi ve Kuramları",
				slug: "ayt-lit-theory",
				sortOrder: 1,
				estimatedHours: 25,
				subtopics: [
					{ name: "Anlam Bilgisi & Metinlerin Sınıflandırılması", slug: "ayt-lit-theo-meaning", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Şiir Bilgisi & Edebi Sanatlar", slug: "ayt-lit-theo-poetry", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.20 },
				],
			},
			{
				name: "Tarihsel Dönemler",
				slug: "ayt-lit-periods",
				sortOrder: 2,
				estimatedHours: 35,
				subtopics: [
					{ name: "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi", slug: "ayt-lit-per-early", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Halk Edebiyatı", slug: "ayt-lit-per-folk", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Divan Edebiyatı", slug: "ayt-lit-per-divan", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.20 },
				],
			},
			{
				name: "Modern Edebiyat ve Akımlar",
				slug: "ayt-lit-modern",
				sortOrder: 3,
				estimatedHours: 40,
				subtopics: [
					{ name: "Tanzimat Edebiyatı", slug: "ayt-lit-mod-tanzimat", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Servet-i Fünun ve Fecr-i Ati Edebiyatı", slug: "ayt-lit-mod-servet", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Milli Edebiyat", slug: "ayt-lit-mod-national", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Cumhuriyet Dönemi Edebiyatı", slug: "ayt-lit-mod-republic", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.22 },
					{ name: "Edebi Akımlar", slug: "ayt-lit-mod-movements", sortOrder: 5, importance: "medium", estimatedQuestionWeight: 0.05 },
				],
			},
		],
	},
	{
		code: "MATH2",
		name: "Matematik (AYT)",
		slug: "ayt-math2",
		color: "#2563eb",
		icon: "Award",
		sortOrder: 2,
		topics: [
			{
				name: "Cebirsel Konular ve Fonksiyonlar",
				slug: "ayt-math-algebra",
				sortOrder: 1,
				estimatedHours: 30,
				subtopics: [
					{ name: "Kümeler & Fonksiyon Kavramı", slug: "ayt-math-alg-functions", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Polinomlar & Çarpanlara Ayırma", slug: "ayt-math-alg-polys", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "İkinci Dereceden Denklemler & Eşitsizlik Sistemleri", slug: "ayt-math-alg-quadratic", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Parabol", slug: "ayt-math-alg-parabola", sortOrder: 4, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Karmaşık Sayılar", slug: "ayt-math-alg-complex", sortOrder: 5, importance: "low", estimatedQuestionWeight: 0.04 },
				],
			},
			{
				name: "Trigonometri ve Logaritma",
				slug: "ayt-math-triglog",
				sortOrder: 2,
				estimatedHours: 35,
				subtopics: [
					{ name: "Trigonometrik Fonksiyonlar & Özdeşlikler", slug: "ayt-math-trig-basics", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Toplam-Fark ve İki Kat Açı Formülleri", slug: "ayt-math-trig-formulas", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Trigonometrik Denklemler", slug: "ayt-math-trig-equations", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Üstel ve Logaritmik Fonksiyonlar", slug: "ayt-math-trig-logarithm", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Gerçek Sayı Dizileri (Aritmetik, Geometrik)", slug: "ayt-math-trig-sequences", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.08 },
				],
			},
			{
				name: "Permütasyon, Olasılık ve Analitik",
				slug: "ayt-math-analytics",
				sortOrder: 3,
				estimatedHours: 25,
				subtopics: [
					{ name: "Sıralama, Seçme, Binom & Koşullu Olasılık", slug: "ayt-math-ana-counting", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Doğrunun ve Çemberin Analitik İncelenmesi", slug: "ayt-math-ana-lines", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Analitik Düzlemde Temel Dönüşümler", slug: "ayt-math-ana-transforms", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.06 },
				],
			},
			{
				name: "Limit, Türev ve İntegral (LTİ)",
				slug: "ayt-math-calculus",
				sortOrder: 4,
				estimatedHours: 60,
				subtopics: [
					{ name: "Limit ve Süreklilik", slug: "ayt-math-calc-limit", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Türev Tanımı ve Kuralları", slug: "ayt-math-calc-derivative", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Türevin Uygulamaları (Maks-Min, Artan-Azalan)", slug: "ayt-math-calc-deriv-apps", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.18 },
					{ name: "Belirsiz ve Belirli İntegral", slug: "ayt-math-calc-integral", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "İntegral ile Alan Hesabı ve Uygulamaları", slug: "ayt-math-calc-int-apps", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
		],
	},
	{
		code: "GEOMETRY2",
		name: "Geometri (AYT)",
		slug: "ayt-geometry2",
		color: "#0284c7",
		icon: "Compass",
		sortOrder: 3,
		topics: [
			{
				name: "AYT Geometri Temelleri",
				slug: "ayt-geo-basics",
				sortOrder: 1,
				estimatedHours: 30,
				subtopics: [
					{ name: "Üçgenler & Benzerlik-Eşlik", slug: "ayt-geo-bas-triangles", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Çokgenler & Dörtgenler (Özel Dörtgenler)", slug: "ayt-geo-bas-polygons", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Çemberde Açı, Uzunluk, Daire Alanı", slug: "ayt-geo-bas-circles", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.18 },
					{ name: "Katı Cisimlerin Yüzey Alanları ve Hacimleri", slug: "ayt-geo-bas-solids", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
		],
	},
	{
		code: "PHYSICS2",
		name: "Fizik (AYT)",
		slug: "ayt-physics2",
		color: "#7c3aed",
		icon: "Atom",
		sortOrder: 4,
		topics: [
			{
				name: "Kuvvet, Hareket ve Enerji",
				slug: "ayt-phys-mechanics",
				sortOrder: 1,
				estimatedHours: 35,
				subtopics: [
					{ name: "Vektörler & Bağıl Hareket", slug: "ayt-phys-mech-vectors", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.06 },
					{ name: "Newton’ın Hareket Yasaları & Bir/İki Boyutta Sabit İvmeli Hareket", slug: "ayt-phys-mech-motion", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "İş, Enerji ve Güç II", slug: "ayt-phys-mech-energy", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "İtme ve Çizgisel Momentum", slug: "ayt-phys-mech-momentum", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Tork, Denge, Denge Şartları & Basit Makineler", slug: "ayt-phys-mech-balance", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.10 },
				],
			},
			{
				name: "Elektrik ve Manyetizma",
				slug: "ayt-phys-electricity",
				sortOrder: 2,
				estimatedHours: 30,
				subtopics: [
					{ name: "Elektriksel Kuvvet, Elektrik Alan & Potansiyel", slug: "ayt-phys-elec-field", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Düzgün Elektrik Alan ve Sığa (Kondansatör)", slug: "ayt-phys-elec-capacitance", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Manyetizma, Elektromanyetik İndükleme, Alternatif Akım & Transformatör", slug: "ayt-phys-elec-induction", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
			{
				name: "Çembersel Hareket ve Dalgalar",
				slug: "ayt-phys-rotational",
				sortOrder: 3,
				estimatedHours: 25,
				subtopics: [
					{ name: "Düzgün Çembersel Hareket, Dönerek Öteleme & Açısal Momentum", slug: "ayt-phys-rot-circular", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Kütle Çekim Kuvveti & Kepler Kanunları", slug: "ayt-phys-rot-kepler", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.06 },
					{ name: "Basit Harmonik Hareket", slug: "ayt-phys-rot-harmonic", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Dalga Mekaniği (Kırınım, Girişim ve Doppler)", slug: "ayt-phys-rot-waves", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.12 },
				],
			},
			{
				name: "Modern Fizik ve Teknolojideki Uygulamalar",
				slug: "ayt-phys-modern",
				sortOrder: 4,
				estimatedHours: 30,
				subtopics: [
					{ name: "Atom Modelleri & Büyük Patlama/Parçacık Fiziği", slug: "ayt-phys-mod-models", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Atom Fiziğine Giriş, Radyoaktivite & Özel Görelilik", slug: "ayt-phys-mod-relativity", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Kara Cisim Işıması, Fotoelektrik Olay & Compton Olayı", slug: "ayt-phys-mod-quantum", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Modern Fiziğin Teknolojideki Uygulamaları (Yarı İletkenler, X-Işınları)", slug: "ayt-phys-mod-tech", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.12 },
				],
			},
		],
	},
	{
		code: "CHEMISTRY2",
		name: "Kimya (AYT)",
		slug: "ayt-chemistry2",
		color: "#ec4899",
		icon: "FlaskConical",
		sortOrder: 5,
		topics: [
			{
				name: "Maddenin Fiziksel Kimyası",
				slug: "ayt-chem-physical",
				sortOrder: 1,
				estimatedHours: 35,
				subtopics: [
					{ name: "Modern Atom Teorisi", slug: "ayt-chem-phy-atom", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Gazlar", slug: "ayt-chem-phy-gases", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Sıvı Çözeltiler ve Çözünürlük", slug: "ayt-chem-phy-solutions", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Kimyasal Tepkimelerde Enerji", slug: "ayt-chem-phy-energy", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Kimyasal Tepkimelerde Hız", slug: "ayt-chem-phy-kinetics", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.10 },
				],
			},
			{
				name: "Denge ve Elektrokimya",
				slug: "ayt-chem-equilibrium",
				sortOrder: 2,
				estimatedHours: 35,
				subtopics: [
					{ name: "Kimyasal Tepkimelerde Denge & Sulu Çözeltilerde Denge (Asit-Baz)", slug: "ayt-chem-eq-acidbase", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.18 },
					{ name: "Çözünürlük Dengesi (KÇÇ)", slug: "ayt-chem-eq-kcc", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Kimya ve Elektrik (Elektrotlar, Piller, Elektroliz)", slug: "ayt-chem-eq-electricity", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
			{
				name: "Karbon Kimyası ve Organik Kimya",
				slug: "ayt-chem-organic",
				sortOrder: 3,
				estimatedHours: 40,
				subtopics: [
					{ name: "Karbon Kimyasına Giriş", slug: "ayt-chem-org-intro", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Organik Bileşikler (Alkan, Alken, Alkin, Alkol, Ester)", slug: "ayt-chem-org-compounds", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.22 },
					{ name: "Enerji Kaynakları ve Bilimsel Gelişmeler", slug: "ayt-chem-org-sources", sortOrder: 3, importance: "low", estimatedQuestionWeight: 0.04 },
				],
			},
		],
	},
	{
		code: "BIOLOGY2",
		name: "Biyoloji (AYT)",
		slug: "ayt-biology2",
		color: "#10b981",
		icon: "Activity",
		sortOrder: 6,
		topics: [
			{
				name: "İnsan Fizyolojisi",
				slug: "ayt-bio-human",
				sortOrder: 1,
				estimatedHours: 45,
				subtopics: [
					{ name: "Denetleyici/Düzenleyici Sistem, Sinir Sistemi & Duyu Organları", slug: "ayt-bio-hum-nervous", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Endokrin Sistem & Destek ve Hareket Sistemi", slug: "ayt-bio-hum-endocrine", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Sindirim Sistemi", slug: "ayt-bio-hum-digestion", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Dolaşım ve Bağışıklık Sistemi", slug: "ayt-bio-hum-circulation", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Solunum Sistemi & Üriner Sistem", slug: "ayt-bio-hum-respiration", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Üreme Sistemi ve Embriyonik Gelişim", slug: "ayt-bio-hum-reproduction", sortOrder: 6, importance: "medium", estimatedQuestionWeight: 0.08 },
				],
			},
			{
				name: "Ekoloji, Genetik ve Enerji",
				slug: "ayt-bio-genetics",
				sortOrder: 2,
				estimatedHours: 35,
				subtopics: [
					{ name: "Komünite ve Popülasyon Ekolojisi", slug: "ayt-bio-gen-ecology", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Genden Proteine (Nükleik Asitler, DNA Eşlenmesi, Protein Sentezi)", slug: "ayt-bio-gen-protein", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.18 },
					{ name: "Canlılarda Enerji Dönüşümleri (Fotosentez, Kemosentez, Solunum)", slug: "ayt-bio-gen-energy", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Bitki Biyolojisi (Dokular, Taşıma, Üreme) & Canlılar ve Çevre", slug: "ayt-bio-gen-plants", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
		],
	},
];
