/** @format */

export const tytSubjects = [
	{
		code: "TURKISH",
		name: "Türkçe",
		slug: "tyt-turkish",
		color: "#e11d48",
		icon: "BookOpen",
		sortOrder: 1,
		topics: [
			{
				name: "Anlam Bilgisi",
				slug: "tyt-turkish-meaning",
				sortOrder: 1,
				estimatedHours: 20,
				subtopics: [
					{ name: "Sözcükte Anlam", slug: "tyt-turkish-meaning-word", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Söz Yorumu", slug: "tyt-turkish-meaning-context", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Deyim ve Atasözü", slug: "tyt-turkish-meaning-idioms", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Cümlede Anlam", slug: "tyt-turkish-meaning-sentence", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.12 },
				],
			},
			{
				name: "Paragraf",
				slug: "tyt-turkish-paragraph",
				sortOrder: 2,
				estimatedHours: 40,
				subtopics: [
					{ name: "Paragrafta Anlatım Teknikleri", slug: "tyt-turkish-para-narrative", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Paragrafta Düşünceyi Geliştirme Yolları", slug: "tyt-turkish-para-development", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Paragrafta Yapı", slug: "tyt-turkish-para-structure", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.20 },
					{ name: "Paragrafta Konu-Ana Düşünce", slug: "tyt-turkish-para-main-idea", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.25 },
					{ name: "Paragrafta Yardımcı Düşünce", slug: "tyt-turkish-para-supporting-idea", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.20 },
				],
			},
			{
				name: "Dil Bilgisi",
				slug: "tyt-turkish-grammar",
				sortOrder: 3,
				estimatedHours: 30,
				subtopics: [
					{ name: "Ses Bilgisi", slug: "tyt-turkish-grammar-phonetics", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.05 },
					{ name: "Sözcükte Yapı/Ekler", slug: "tyt-turkish-grammar-structure", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Sözcük Türleri (İsim, Zamir, Sıfat, Zarf)", slug: "tyt-turkish-grammar-speech-parts", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Edat – Bağlaç – Ünlem", slug: "tyt-turkish-grammar-connectors", sortOrder: 4, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Fiiller & Ek Fiil", slug: "tyt-turkish-grammar-verbs", sortOrder: 5, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Fiilimsi", slug: "tyt-turkish-grammar-gerunds", sortOrder: 6, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Fiilde Çatı", slug: "tyt-turkish-grammar-verb-voice", sortOrder: 7, importance: "low", estimatedQuestionWeight: 0.02 },
					{ name: "Sözcük Grupları", slug: "tyt-turkish-grammar-word-groups", sortOrder: 8, importance: "medium", estimatedQuestionWeight: 0.04 },
					{ name: "Cümlenin Ögeleri", slug: "tyt-turkish-grammar-sentence-parts", sortOrder: 9, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Cümle Türleri", slug: "tyt-turkish-grammar-sentence-types", sortOrder: 10, importance: "low", estimatedQuestionWeight: 0.03 },
				],
			},
			{
				name: "Yazım, Noktalama ve Bozukluklar",
				slug: "tyt-turkish-orthography",
				sortOrder: 4,
				estimatedHours: 20,
				subtopics: [
					{ name: "Yazım Kuralları", slug: "tyt-turkish-ortho-spelling", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Noktalama İşaretleri", slug: "tyt-turkish-ortho-punctuation", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Anlatım Bozukluğu", slug: "tyt-turkish-ortho-faults", sortOrder: 3, importance: "low", estimatedQuestionWeight: 0.03 },
				],
			},
		],
	},
	{
		code: "MATHEMATICS",
		name: "Temel Matematik",
		slug: "tyt-mathematics",
		color: "#0ea5e9",
		icon: "Calculator",
		sortOrder: 2,
		topics: [
			{
				name: "Temel Sayılar ve İşlemler",
				slug: "tyt-math-numbers",
				sortOrder: 1,
				estimatedHours: 35,
				subtopics: [
					{ name: "Temel Kavramlar", slug: "tyt-math-num-concepts", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Sayı Basamakları", slug: "tyt-math-num-digits", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Bölme ve Bölünebilme", slug: "tyt-math-num-division", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.04 },
					{ name: "EBOB – EKOK", slug: "tyt-math-num-gcd", sortOrder: 4, importance: "low", estimatedQuestionWeight: 0.03 },
					{ name: "Rasyonel Sayılar", slug: "tyt-math-num-rational", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.08 },
				],
			},
			{
				name: "Cebirsel İfadeler ve Denklemler",
				slug: "tyt-math-algebra",
				sortOrder: 2,
				estimatedHours: 30,
				subtopics: [
					{ name: "Basit Eşitsizlikler", slug: "tyt-math-alg-inequality", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Mutlak Değer", slug: "tyt-math-alg-absolute", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.06 },
					{ name: "Üslü Sayılar", slug: "tyt-math-alg-exponent", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Köklü Sayılar", slug: "tyt-math-alg-roots", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Çarpanlara Ayırma", slug: "tyt-math-alg-factoring", sortOrder: 5, importance: "medium", estimatedQuestionWeight: 0.04 },
					{ name: "Oran Orantı", slug: "tyt-math-alg-ratio", sortOrder: 6, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Denklem Çözme", slug: "tyt-math-alg-equations", sortOrder: 7, importance: "medium", estimatedQuestionWeight: 0.04 },
				],
			},
			{
				name: "Problemler",
				slug: "tyt-math-problems",
				sortOrder: 3,
				estimatedHours: 50,
				subtopics: [
					{ name: "Sayı Kesir Problemleri", slug: "tyt-math-prob-numbers", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Yaş Problemleri", slug: "tyt-math-prob-age", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Hareket Hız Problemleri", slug: "tyt-math-prob-speed", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "İşçi Emek Problemleri", slug: "tyt-math-prob-work", sortOrder: 4, importance: "low", estimatedQuestionWeight: 0.03 },
					{ name: "Yüzde Kar Zarar Problemleri", slug: "tyt-math-prob-percent", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Karışım Problemleri", slug: "tyt-math-prob-mixture", sortOrder: 6, importance: "low", estimatedQuestionWeight: 0.03 },
					{ name: "Grafik Problemleri", slug: "tyt-math-prob-graph", sortOrder: 7, importance: "medium", estimatedQuestionWeight: 0.06 },
					{ name: "Rutin Olmayan Problemler", slug: "tyt-math-prob-novel", sortOrder: 8, importance: "high", estimatedQuestionWeight: 0.10 },
				],
			},
			{
				name: "Kümeler ve Fonksiyonlar",
				slug: "tyt-math-functions",
				sortOrder: 4,
				estimatedHours: 25,
				subtopics: [
					{ name: "Kümeler – Kartezyen Çarpım", slug: "tyt-math-fun-sets", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Mantık", slug: "tyt-math-fun-logic", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.04 },
					{ name: "Fonksiyonlar", slug: "tyt-math-fun-basic", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Polinomlar", slug: "tyt-math-fun-polys", sortOrder: 4, importance: "medium", estimatedQuestionWeight: 0.04 },
					{ name: "2. Dereceden Denklemler", slug: "tyt-math-fun-quadratic", sortOrder: 5, importance: "low", estimatedQuestionWeight: 0.03 },
				],
			},
			{
				name: "Veri, Sayma ve Olasılık",
				slug: "tyt-math-combinatorics",
				sortOrder: 5,
				estimatedHours: 25,
				subtopics: [
					{ name: "Permütasyon ve Kombinasyon", slug: "tyt-math-comb-perms", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Olasılık", slug: "tyt-math-comb-prob", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.08 },
					{ name: "Veri – İstatistik", slug: "tyt-math-comb-data", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.05 },
				],
			},
		],
	},
	{
		code: "GEOMETRY",
		name: "Geometri",
		slug: "tyt-geometry",
		color: "#06b6d4",
		icon: "Compass",
		sortOrder: 3,
		topics: [
			{
				name: "Üçgenler",
				slug: "tyt-geo-triangles",
				sortOrder: 1,
				estimatedHours: 30,
				subtopics: [
					{ name: "Doğruda ve Üçgende Açılar", slug: "tyt-geo-tri-angles", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Özel Üçgenler (Dik, İkizkenar, Eşkenar)", slug: "tyt-geo-tri-special", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Üçgende Yardımcı Elemanlar (Açıortay, Kenarortay)", slug: "tyt-geo-tri-helpers", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.06 },
					{ name: "Üçgende Eşlik ve Benzerlik", slug: "tyt-geo-tri-similarity", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Üçgende Alan", slug: "tyt-geo-tri-area", sortOrder: 5, importance: "high", estimatedQuestionWeight: 0.08 },
				],
			},
			{
				name: "Çokgenler ve Dörtgenler",
				slug: "tyt-geo-polygons",
				sortOrder: 2,
				estimatedHours: 25,
				subtopics: [
					{ name: "Çokgenler", slug: "tyt-geo-poly-basic", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.05 },
					{ name: "Özel Dörtgenler (Paralelkenar, Eşkenar Dörtgen, Deltoid)", slug: "tyt-geo-poly-special", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Dikdörtgen ve Kare", slug: "tyt-geo-poly-rectangle-square", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Yamuk", slug: "tyt-geo-poly-trapezoid", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.08 },
				],
			},
			{
				name: "Çember ve Daire",
				slug: "tyt-geo-circles",
				sortOrder: 3,
				estimatedHours: 20,
				subtopics: [
					{ name: "Çemberde Açı ve Uzunluk", slug: "tyt-geo-circle-properties", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Dairede Çevre ve Alan", slug: "tyt-geo-circle-area", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
				],
			},
			{
				name: "Katı Cisimler ve Analitik",
				slug: "tyt-geo-solids",
				sortOrder: 4,
				estimatedHours: 25,
				subtopics: [
					{ name: "Katı Cisimler (Prizma, Piramit, Küre)", slug: "tyt-geo-sol-solids", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Noktanın ve Doğrunun Analitiği", slug: "tyt-geo-sol-analytic", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
				],
			},
		],
	},
	{
		code: "PHYSICS",
		name: "Fizik",
		slug: "tyt-physics",
		color: "#8b5cf6",
		icon: "Zap",
		sortOrder: 4,
		topics: [
			{
				name: "Fizik Bilimi ve Madde",
				slug: "tyt-phys-matter",
				sortOrder: 1,
				estimatedHours: 15,
				subtopics: [
					{ name: "Fizik Bilimine Giriş", slug: "tyt-phys-mat-intro", sortOrder: 1, importance: "low", estimatedQuestionWeight: 0.03 },
					{ name: "Madde ve Özellikleri (Kütle, Hacim, Özkütle)", slug: "tyt-phys-mat-properties", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Sıvıların Kaldırma Kuvveti", slug: "tyt-phys-mat-buoyancy", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Basınç (Katı, Sıvı, Gaz Basıncı)", slug: "tyt-phys-mat-pressure", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.12 },
				],
			},
			{
				name: "Mekanik ve Termodinamik",
				slug: "tyt-phys-mechanics",
				sortOrder: 2,
				estimatedHours: 20,
				subtopics: [
					{ name: "Hareket ve Kuvvet", slug: "tyt-phys-mech-motion", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "İş, Güç ve Enerji", slug: "tyt-phys-mech-energy", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Isı, Sıcaklık ve Genleşme", slug: "tyt-phys-mech-heat", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
			{
				name: "Elektrik, Dalgalar ve Optik",
				slug: "tyt-phys-waves",
				sortOrder: 3,
				estimatedHours: 25,
				subtopics: [
					{ name: "Elektrostatik", slug: "tyt-phys-wav-electrostatics", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.06 },
					{ name: "Elektrik Akımı, Devreler & Manyetizma", slug: "tyt-phys-wav-circuits", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Dalgalar (Ses, Deprem, Su)", slug: "tyt-phys-wav-waves", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Optik (Yansıma, Kırılma, Mercekler)", slug: "tyt-phys-wav-optics", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.20 },
				],
			},
		],
	},
	{
		code: "CHEMISTRY",
		name: "Kimya",
		slug: "tyt-chemistry",
		color: "#ec4899",
		icon: "FlaskConical",
		sortOrder: 5,
		topics: [
			{
				name: "Kimya Bilimi ve Maddenin Yapısı",
				slug: "tyt-chem-structure",
				sortOrder: 1,
				estimatedHours: 20,
				subtopics: [
					{ name: "Kimya Bilimi", slug: "tyt-chem-struct-science", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Atomun Yapısı & Periyodik Sistem", slug: "tyt-chem-struct-periodic", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Kimyasal Türler Arası Etkileşimler", slug: "tyt-chem-struct-bonds", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Maddenin Halleri", slug: "tyt-chem-struct-states", sortOrder: 4, importance: "medium", estimatedQuestionWeight: 0.10 },
				],
			},
			{
				name: "Kimyanın Kanunları ve Karışımlar",
				slug: "tyt-chem-equations",
				sortOrder: 2,
				estimatedHours: 20,
				subtopics: [
					{ name: "Kimyanın Temel Kanunları & Hesaplamalar", slug: "tyt-chem-eq-laws", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Karışımlar (Ayrıştırma Yöntemleri)", slug: "tyt-chem-eq-mixtures", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
				],
			},
			{
				name: "Asitler, Bazlar ve Günlük Kimya",
				slug: "tyt-chem-applications",
				sortOrder: 3,
				estimatedHours: 15,
				subtopics: [
					{ name: "Asit, Baz ve Tuz", slug: "tyt-chem-app-acidbase", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Kimya Her Yerde", slug: "tyt-chem-app-everywhere", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.08 },
				],
			},
		],
	},
	{
		code: "BIOLOGY",
		name: "Biyoloji",
		slug: "tyt-biology",
		color: "#22c55e",
		icon: "Activity",
		sortOrder: 6,
		topics: [
			{
				name: "Hücre ve Organizma",
				slug: "tyt-bio-cell",
				sortOrder: 1,
				estimatedHours: 20,
				subtopics: [
					{ name: "Canlıların Ortak Özellikleri & Temel Bileşenleri", slug: "tyt-bio-cell-components", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Hücre Yapısı ve Hücre Zarından Madde Geçişleri", slug: "tyt-bio-cell-structure", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Canlıların Sınıflandırılması", slug: "tyt-bio-cell-taxonomy", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.12 },
				],
			},
			{
				name: "Üreme, Kalıtım ve Ekoloji",
				slug: "tyt-bio-genetics",
				sortOrder: 2,
				estimatedHours: 20,
				subtopics: [
					{ name: "Hücre Bölünmeleri (Mitoz, Mayoz) ve Üreme", slug: "tyt-bio-gen-division", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Kalıtımın Genel İlkeleri", slug: "tyt-bio-gen-inheritance", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.20 },
					{ name: "Ekosistem Ekolojisi & Çevre Sorunları", slug: "tyt-bio-gen-ecology", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
		],
	},
	{
		code: "HISTORY",
		name: "Tarih",
		slug: "tyt-history",
		color: "#f59e0b",
		icon: "Scroll",
		sortOrder: 7,
		topics: [
			{
				name: "Tarih ve İlk Dönemler",
				slug: "tyt-hist-early",
				sortOrder: 1,
				estimatedHours: 15,
				subtopics: [
					{ name: "Tarih ve Zaman & İlk Çağ Uygarlıkları", slug: "tyt-hist-early-concepts", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "İlk ve Orta Çağlarda Türk Dünyası", slug: "tyt-hist-early-turkish", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "İslam Medeniyetinin Doğuşu & İlk Türk İslam Devletleri", slug: "tyt-hist-early-islam", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
			{
				name: "Osmanlı Tarihi",
				slug: "tyt-hist-ottoman",
				sortOrder: 2,
				estimatedHours: 25,
				subtopics: [
					{ name: "Beylikten Devlete & Dünya Gücü Osmanlı", slug: "tyt-hist-ott-rise", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Osmanlı Toplum Düzeni, Merkez ve Ordu Teşkilatı", slug: "tyt-hist-ott-culture", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.10 },
					{ name: "Değişen Dünya Dengeleri ve Osmanlı Siyaseti (1774-1914)", slug: "tyt-hist-ott-decline", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
			{
				name: "Milli Mücadele ve İnkılap Tarihi",
				slug: "tyt-hist-republic",
				sortOrder: 3,
				estimatedHours: 20,
				subtopics: [
					{ name: "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya", slug: "tyt-hist-rep-ww1", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.12 },
					{ name: "Milli Mücadele Dönemi (Kongreler, Cepheler)", slug: "tyt-hist-rep-independence", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.20 },
					{ name: "Atatürkçülük ve Türk İnkılabı", slug: "tyt-hist-rep-reforms", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.18 },
				],
			},
		],
	},
	{
		code: "GEOGRAPHY",
		name: "Coğrafya",
		slug: "tyt-geography",
		color: "#10b981",
		icon: "Globe",
		sortOrder: 8,
		topics: [
			{
				name: "Doğal Sistemler",
				slug: "tyt-geog-natural",
				sortOrder: 1,
				estimatedHours: 20,
				subtopics: [
					{ name: "Doğa ve İnsan & Harita Bilgisi", slug: "tyt-geog-nat-intro", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.10 },
					{ name: "Dünya'nın Şekli ve Hareketleri & Coğrafi Konum", slug: "tyt-geog-nat-earth", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Atmosfer, İklim Bilgisi, Nem ve Yağış", slug: "tyt-geog-nat-climate", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.20 },
					{ name: "İç Kuvvetler / Dış Kuvvetler & Türkiye Yer Şekilleri", slug: "tyt-geog-nat-forces", sortOrder: 4, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
			{
				name: "Beşeri Sistemler ve Çevre",
				slug: "tyt-geog-human",
				sortOrder: 2,
				estimatedHours: 15,
				subtopics: [
					{ name: "Nüfus, Yerleşme & Göç (Türkiye ve Dünya)", slug: "tyt-geog-hum-population", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.20 },
					{ name: "Ekonomik Faaliyetler & Bölgeler", slug: "tyt-geog-hum-economy", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.08 },
					{ name: "Çevre, Toplum & Doğal Afetler", slug: "tyt-geog-hum-disasters", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.15 },
				],
			},
		],
	},
	{
		code: "PHILOSOPHY",
		name: "Felsefe",
		slug: "tyt-philosophy",
		color: "#a855f7",
		icon: "Brain",
		sortOrder: 9,
		topics: [
			{
				name: "Felsefenin Temel Alanları",
				slug: "tyt-phil-fields",
				sortOrder: 1,
				estimatedHours: 15,
				subtopics: [
					{ name: "Felsefenin Konusu & Bilgi Felsefesi", slug: "tyt-phil-fld-knowledge", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.15 },
					{ name: "Varlık Felsefesi (Ontoloji)", slug: "tyt-phil-fld-existence", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.10 },
					{ name: "Ahlak, Sanat, Din, Siyaset & Bilim Felsefesi", slug: "tyt-phil-fld-others", sortOrder: 3, importance: "high", estimatedQuestionWeight: 0.25 },
				],
			},
			{
				name: "Felsefe Tarihi",
				slug: "tyt-phil-history",
				sortOrder: 2,
				estimatedHours: 15,
				subtopics: [
					{ name: "İlk Çağ Felsefesi (M.Ö. 6. YY - M.S. 2. YY)", slug: "tyt-phil-hist-ancient", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.10 },
					{ name: "Orta Çağ & Modern Çağ Felsefeleri", slug: "tyt-phil-hist-medieval", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.20 },
					{ name: "20. Yüzyıl Felsefesi", slug: "tyt-phil-hist-modern", sortOrder: 3, importance: "medium", estimatedQuestionWeight: 0.10 },
				],
			},
		],
	},
	{
		code: "RELIGION",
		name: "Din Kültürü ve Ahlak Bilgisi",
		slug: "tyt-religion",
		color: "#fbbf24",
		icon: "Heart",
		sortOrder: 10,
		topics: [
			{
				name: "Temel İnançlar ve İbadet",
				slug: "tyt-rel-belief",
				sortOrder: 1,
				estimatedHours: 12,
				subtopics: [
					{ name: "Bilgi ve İnanç & İslamda İbadetler", slug: "tyt-rel-bel-worship", sortOrder: 1, importance: "high", estimatedQuestionWeight: 0.25 },
					{ name: "Ahlak ve Değerler & Allah İnsan İlişkisi", slug: "tyt-rel-bel-ethics", sortOrder: 2, importance: "high", estimatedQuestionWeight: 0.25 },
				],
			},
			{
				name: "Peygamberlik ve İslam Düşüncesi",
				slug: "tyt-rel-prophet",
				sortOrder: 2,
				estimatedHours: 12,
				subtopics: [
					{ name: "Hz. Muhammed (S.A.V.) & Vahiy ve Akıl", slug: "tyt-rel-prop-muhammad", sortOrder: 1, importance: "medium", estimatedQuestionWeight: 0.20 },
					{ name: "İslam Düşüncesinde Yorumlar ve Mezhepler", slug: "tyt-rel-prop-schools", sortOrder: 2, importance: "medium", estimatedQuestionWeight: 0.15 },
					{ name: "Din, Kültür, Medeniyet & Yaşayan Dinler", slug: "tyt-rel-prop-civilizations", sortOrder: 3, importance: "low", estimatedQuestionWeight: 0.10 },
				],
			},
		],
	},
];
