export const topUniversities = [
	"Boğaziçi University",
	"Middle East Technical University (METU)",
	"Istanbul Technical University (ITU)",
	"Koç University",
	"Bilkent University",
	"Sabancı University",
	"Hacettepe University",
	"Istanbul University",
	"Ankara University",
	"Ege University",
	"Dokuz Eylül University",
	"Yıldız Technical University (YTU)",
	"Marmara University",
	"Galatasaray University",
	"TOBB ETU",
];

export const topDepartments = [
	"Computer Engineering",
	"Medicine",
	"Electrical and Electronics Engineering",
	"Industrial Engineering",
	"Mechanical Engineering",
	"Law",
	"Business Administration",
	"Economics",
	"Molecular Biology and Genetics",
	"Psychology",
	"Architecture",
	"Civil Engineering",
	"Chemical Engineering",
	"Mathematics",
	"English Language and Literature",
];
